
# Name of website
title: Meteo Website

url: https://meteo-team.github.io
baseurl: /meteo-website

# redirect_from:
#   - /pages/app-downloads/

# permalink: /pages/app-downloads
# redirect_to:
#   - https://meteo-team.github.io/meteo-website/app-download.html

# https://github.com/jekyll/jekyll-redirect-from

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
